{{- if .Values.squid.authentication.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squid.fullname" . }}
  labels:
    {{- include "squid.labels" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: |
  {{- range .Values.squid.authentication.users }}
    {{- htpasswd .name .password | nindent 4 }}
  {{- end }}
{{- end }}
