apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "password-pusher.fullname" . }}
  labels:
    {{- include "password-pusher.labels" . | nindent 4 }}
data:
{{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
{{- end }}
