apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ddns-updater.fullname" . }}
  labels:
    {{- include "ddns-updater.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "settings":
      {{- toPrettyJson .Values.config | nindent 8 }}
    }

